package tables

import (
	"database/sql"
	"fmt"
	"log"
)

// CreateUserTable 좌석 관리 테이블 및 인덱스를 생성합니다.
// 함수 이름을 대문자로 시작하여 외부에서 접근 가능하게 만듭니다.
// 사용자 정보 테이블
func CreateUserTable(db *sql.DB) error {
	log.Println("user_table 테이블을 생성합니다...")

	// 테이블 생성
	createBaseTableQuery := `CREATE TABLE IF NOT EXISTS user_table();`

	_, err := db.Exec(createBaseTableQuery)
	if err != nil {
		return err
	}
	log.Println("user_table 테이블 기본 구조 생성 완료")

	tableName := "user_table"
	alterPrefix := fmt.Sprintf("ALTER TABLE %s ADD COLUMN IF NOT EXISTS ", tableName)

	// 각 필드 개별 추가
	fieldDefinitions := []string{
		// 기본키
		"serial_number BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;",
		// 이름
		"name TEXT NOT NULL;",
		// 비밀번호
		"password TEXT NOT NULL;",
		// 이메일
		"email TEXT UNIQUE NOT NULL;",
		// 전화번호1
		"phone1 TEXT;",
		// 전화번호2
		"phone2 TEXT;",
		// 전화번호3
		"phone3 TEXT;",
		// 생년월일
		"birth_date DATE;",
		// 성별
		"gender TEXT;",
		// 우편번호
		"postal_code TEXT;",
		// 주소
		"address TEXT;",
		// 약관 동의
		"terms_agreed BOOLEAN DEFAULT FALSE;",
		// 개인정보 동의
		"privacy_agreed BOOLEAN DEFAULT FALSE;",
		// 마케팅 동의
		"marketing_agreed BOOLEAN DEFAULT FALSE;",
		// 프로필 이미지
		"profile_image TEXT;",
		// 생성일
		"created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;",
		// 수정일
		"updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;",
	}

	// 각 필드 추가 쿼리 생성
	fieldQueries := make([]string, len(fieldDefinitions))
	for i, field := range fieldDefinitions {
		fieldQueries[i] = alterPrefix + field + ";"
	}

	// 각 필드 추가 실행 및 진행 상황 로깅
	for i, query := range fieldQueries {
		_, err = db.Exec(query)
		if err != nil {
			return err
		}
		// if (i+1)%5 == 0 || i == len(fieldQueries)-1 {
		log.Printf("user_table 필드 추가 진행 중: %d/%d 완료", i+1, len(fieldQueries))
		// }
	}

	// 인덱스 생성 쿼리 목록
	indexQueries := []string{
		`CREATE INDEX IF NOT EXISTS idx_serial_number ON user_table (serial_number);`,
	}

	// 인덱스 생성 실행
	for _, query := range indexQueries {
		_, err = db.Exec(query)
		if err != nil {
			return err
		}
	}

	log.Println("user_table 테이블과 인덱스가 성공적으로 생성되었습니다.")
	return nil
}
